// Code generated by protoc-gen-go.
// source: isserverpb.proto
// DO NOT EDIT!

/*
Package isserverpb is a generated protocol buffer package.

It is generated from these files:
	isserverpb.proto

It has these top-level messages:
	UserStatusChangeRequest
*/
package isserverpb

import proto "github.com/golang/protobuf/proto"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = math.Inf

type UserStatusChangeRequest_EventType int32

const (
	UserStatusChangeRequest_ONLINE  UserStatusChangeRequest_EventType = 0
	UserStatusChangeRequest_OFFLINE UserStatusChangeRequest_EventType = 1
)

var UserStatusChangeRequest_EventType_name = map[int32]string{
	0: "ONLINE",
	1: "OFFLINE",
}
var UserStatusChangeRequest_EventType_value = map[string]int32{
	"ONLINE":  0,
	"OFFLINE": 1,
}

func (x UserStatusChangeRequest_EventType) Enum() *UserStatusChangeRequest_EventType {
	p := new(UserStatusChangeRequest_EventType)
	*p = x
	return p
}
func (x UserStatusChangeRequest_EventType) String() string {
	return proto.EnumName(UserStatusChangeRequest_EventType_name, int32(x))
}
func (x *UserStatusChangeRequest_EventType) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(UserStatusChangeRequest_EventType_value, data, "UserStatusChangeRequest_EventType")
	if err != nil {
		return err
	}
	*x = UserStatusChangeRequest_EventType(value)
	return nil
}

type UserStatusChangeRequest_FieldType int32

const (
	UserStatusChangeRequest_UID      UserStatusChangeRequest_FieldType = 0
	UserStatusChangeRequest_DEVICEID UserStatusChangeRequest_FieldType = 1
)

var UserStatusChangeRequest_FieldType_name = map[int32]string{
	0: "UID",
	1: "DEVICEID",
}
var UserStatusChangeRequest_FieldType_value = map[string]int32{
	"UID":      0,
	"DEVICEID": 1,
}

func (x UserStatusChangeRequest_FieldType) Enum() *UserStatusChangeRequest_FieldType {
	p := new(UserStatusChangeRequest_FieldType)
	*p = x
	return p
}
func (x UserStatusChangeRequest_FieldType) String() string {
	return proto.EnumName(UserStatusChangeRequest_FieldType_name, int32(x))
}
func (x *UserStatusChangeRequest_FieldType) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(UserStatusChangeRequest_FieldType_value, data, "UserStatusChangeRequest_FieldType")
	if err != nil {
		return err
	}
	*x = UserStatusChangeRequest_FieldType(value)
	return nil
}

type UserStatusChangeRequest struct {
	EventType        *UserStatusChangeRequest_EventType `protobuf:"varint,1,req,name=event_type,enum=isserverpb.UserStatusChangeRequest_EventType" json:"event_type,omitempty"`
	FieldType        *UserStatusChangeRequest_FieldType `protobuf:"varint,2,req,name=field_type,enum=isserverpb.UserStatusChangeRequest_FieldType" json:"field_type,omitempty"`
	Uid              *uint64                            `protobuf:"varint,3,opt,name=uid" json:"uid,omitempty"`
	DeviceId         []byte                             `protobuf:"bytes,4,opt,name=device_id" json:"device_id,omitempty"`
	XXX_unrecognized []byte                             `json:"-"`
}

func (m *UserStatusChangeRequest) Reset()         { *m = UserStatusChangeRequest{} }
func (m *UserStatusChangeRequest) String() string { return proto.CompactTextString(m) }
func (*UserStatusChangeRequest) ProtoMessage()    {}

func (m *UserStatusChangeRequest) GetEventType() UserStatusChangeRequest_EventType {
	if m != nil && m.EventType != nil {
		return *m.EventType
	}
	return UserStatusChangeRequest_ONLINE
}

func (m *UserStatusChangeRequest) GetFieldType() UserStatusChangeRequest_FieldType {
	if m != nil && m.FieldType != nil {
		return *m.FieldType
	}
	return UserStatusChangeRequest_UID
}

func (m *UserStatusChangeRequest) GetUid() uint64 {
	if m != nil && m.Uid != nil {
		return *m.Uid
	}
	return 0
}

func (m *UserStatusChangeRequest) GetDeviceId() []byte {
	if m != nil {
		return m.DeviceId
	}
	return nil
}

func init() {
	proto.RegisterEnum("isserverpb.UserStatusChangeRequest_EventType", UserStatusChangeRequest_EventType_name, UserStatusChangeRequest_EventType_value)
	proto.RegisterEnum("isserverpb.UserStatusChangeRequest_FieldType", UserStatusChangeRequest_FieldType_name, UserStatusChangeRequest_FieldType_value)
}
