// Code generated by protoc-gen-go.
// source: statuspb.proto
// DO NOT EDIT!

/*
Package statuspb is a generated protocol buffer package.

It is generated from these files:
	statuspb.proto

It has these top-level messages:
	StatusRequest
	StatusResponse
	StatusQueryResult
	StatusQueryResponse
	StatusMap
	StringToIntMap
	AnonymousMap
*/
package statuspb

import proto "github.com/golang/protobuf/proto"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = math.Inf

type StatusRequest_Type int32

const (
	StatusRequest_ONLINE            StatusRequest_Type = 0
	StatusRequest_OFFLINE           StatusRequest_Type = 1
	StatusRequest_GET               StatusRequest_Type = 2
	StatusRequest_REPLICATE_ONLINE  StatusRequest_Type = 3
	StatusRequest_REPLICATE_OFFLINE StatusRequest_Type = 4
)

var StatusRequest_Type_name = map[int32]string{
	0: "ONLINE",
	1: "OFFLINE",
	2: "GET",
	3: "REPLICATE_ONLINE",
	4: "REPLICATE_OFFLINE",
}
var StatusRequest_Type_value = map[string]int32{
	"ONLINE":            0,
	"OFFLINE":           1,
	"GET":               2,
	"REPLICATE_ONLINE":  3,
	"REPLICATE_OFFLINE": 4,
}

func (x StatusRequest_Type) Enum() *StatusRequest_Type {
	p := new(StatusRequest_Type)
	*p = x
	return p
}
func (x StatusRequest_Type) String() string {
	return proto.EnumName(StatusRequest_Type_name, int32(x))
}
func (x *StatusRequest_Type) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(StatusRequest_Type_value, data, "StatusRequest_Type")
	if err != nil {
		return err
	}
	*x = StatusRequest_Type(value)
	return nil
}

type StatusRequest_FieldType int32

const (
	StatusRequest_UID      StatusRequest_FieldType = 0
	StatusRequest_DEVICEID StatusRequest_FieldType = 1
)

var StatusRequest_FieldType_name = map[int32]string{
	0: "UID",
	1: "DEVICEID",
}
var StatusRequest_FieldType_value = map[string]int32{
	"UID":      0,
	"DEVICEID": 1,
}

func (x StatusRequest_FieldType) Enum() *StatusRequest_FieldType {
	p := new(StatusRequest_FieldType)
	*p = x
	return p
}
func (x StatusRequest_FieldType) String() string {
	return proto.EnumName(StatusRequest_FieldType_name, int32(x))
}
func (x *StatusRequest_FieldType) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(StatusRequest_FieldType_value, data, "StatusRequest_FieldType")
	if err != nil {
		return err
	}
	*x = StatusRequest_FieldType(value)
	return nil
}

type StatusResponse_Type int32

const (
	StatusResponse_OK            StatusResponse_Type = 0
	StatusResponse_FORCE_OFFLINE StatusResponse_Type = 1
)

var StatusResponse_Type_name = map[int32]string{
	0: "OK",
	1: "FORCE_OFFLINE",
}
var StatusResponse_Type_value = map[string]int32{
	"OK":            0,
	"FORCE_OFFLINE": 1,
}

func (x StatusResponse_Type) Enum() *StatusResponse_Type {
	p := new(StatusResponse_Type)
	*p = x
	return p
}
func (x StatusResponse_Type) String() string {
	return proto.EnumName(StatusResponse_Type_name, int32(x))
}
func (x *StatusResponse_Type) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(StatusResponse_Type_value, data, "StatusResponse_Type")
	if err != nil {
		return err
	}
	*x = StatusResponse_Type(value)
	return nil
}

type StatusQueryResponse_Type int32

const (
	StatusQueryResponse_FOUND     StatusQueryResponse_Type = 0
	StatusQueryResponse_NOT_FOUND StatusQueryResponse_Type = 1
)

var StatusQueryResponse_Type_name = map[int32]string{
	0: "FOUND",
	1: "NOT_FOUND",
}
var StatusQueryResponse_Type_value = map[string]int32{
	"FOUND":     0,
	"NOT_FOUND": 1,
}

func (x StatusQueryResponse_Type) Enum() *StatusQueryResponse_Type {
	p := new(StatusQueryResponse_Type)
	*p = x
	return p
}
func (x StatusQueryResponse_Type) String() string {
	return proto.EnumName(StatusQueryResponse_Type_name, int32(x))
}
func (x *StatusQueryResponse_Type) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(StatusQueryResponse_Type_value, data, "StatusQueryResponse_Type")
	if err != nil {
		return err
	}
	*x = StatusQueryResponse_Type(value)
	return nil
}

type StatusRequest struct {
	ReqType    *StatusRequest_Type      `protobuf:"varint,1,req,name=req_type,enum=statuspb.StatusRequest_Type" json:"req_type,omitempty"`
	FieldType  *StatusRequest_FieldType `protobuf:"varint,2,req,name=field_type,enum=statuspb.StatusRequest_FieldType" json:"field_type,omitempty"`
	Uid        *uint64                  `protobuf:"varint,3,opt,name=uid" json:"uid,omitempty"`
	AppVersion *string                  `protobuf:"bytes,4,opt,name=app_version" json:"app_version,omitempty"`
	DeviceId   *string                  `protobuf:"bytes,5,opt,name=device_id" json:"device_id,omitempty"`
	NetId      *uint32                  `protobuf:"varint,6,opt,name=net_id" json:"net_id,omitempty"`
	Timestamp  *uint64                  `protobuf:"varint,7,opt,name=timestamp" json:"timestamp,omitempty"`
	// for push server only
	ResumeNetId *uint32 `protobuf:"varint,8,opt,name=resume_net_id" json:"resume_net_id,omitempty"`
	// for replication server only
	ServerId         *uint32 `protobuf:"varint,9,req,name=server_id" json:"server_id,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *StatusRequest) Reset()         { *m = StatusRequest{} }
func (m *StatusRequest) String() string { return proto.CompactTextString(m) }
func (*StatusRequest) ProtoMessage()    {}

func (m *StatusRequest) GetReqType() StatusRequest_Type {
	if m != nil && m.ReqType != nil {
		return *m.ReqType
	}
	return StatusRequest_ONLINE
}

func (m *StatusRequest) GetFieldType() StatusRequest_FieldType {
	if m != nil && m.FieldType != nil {
		return *m.FieldType
	}
	return StatusRequest_UID
}

func (m *StatusRequest) GetUid() uint64 {
	if m != nil && m.Uid != nil {
		return *m.Uid
	}
	return 0
}

func (m *StatusRequest) GetAppVersion() string {
	if m != nil && m.AppVersion != nil {
		return *m.AppVersion
	}
	return ""
}

func (m *StatusRequest) GetDeviceId() string {
	if m != nil && m.DeviceId != nil {
		return *m.DeviceId
	}
	return ""
}

func (m *StatusRequest) GetNetId() uint32 {
	if m != nil && m.NetId != nil {
		return *m.NetId
	}
	return 0
}

func (m *StatusRequest) GetTimestamp() uint64 {
	if m != nil && m.Timestamp != nil {
		return *m.Timestamp
	}
	return 0
}

func (m *StatusRequest) GetResumeNetId() uint32 {
	if m != nil && m.ResumeNetId != nil {
		return *m.ResumeNetId
	}
	return 0
}

func (m *StatusRequest) GetServerId() uint32 {
	if m != nil && m.ServerId != nil {
		return *m.ServerId
	}
	return 0
}

type StatusResponse struct {
	RespType         *StatusResponse_Type `protobuf:"varint,1,req,name=resp_type,enum=statuspb.StatusResponse_Type" json:"resp_type,omitempty"`
	NetId            *uint32              `protobuf:"varint,2,req,name=net_id" json:"net_id,omitempty"`
	XXX_unrecognized []byte               `json:"-"`
}

func (m *StatusResponse) Reset()         { *m = StatusResponse{} }
func (m *StatusResponse) String() string { return proto.CompactTextString(m) }
func (*StatusResponse) ProtoMessage()    {}

func (m *StatusResponse) GetRespType() StatusResponse_Type {
	if m != nil && m.RespType != nil {
		return *m.RespType
	}
	return StatusResponse_OK
}

func (m *StatusResponse) GetNetId() uint32 {
	if m != nil && m.NetId != nil {
		return *m.NetId
	}
	return 0
}

type StatusQueryResult struct {
	RemoteNetId      *uint32 `protobuf:"varint,1,req,name=remote_net_id" json:"remote_net_id,omitempty"`
	Ip               *uint32 `protobuf:"varint,2,req,name=ip" json:"ip,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *StatusQueryResult) Reset()         { *m = StatusQueryResult{} }
func (m *StatusQueryResult) String() string { return proto.CompactTextString(m) }
func (*StatusQueryResult) ProtoMessage()    {}

func (m *StatusQueryResult) GetRemoteNetId() uint32 {
	if m != nil && m.RemoteNetId != nil {
		return *m.RemoteNetId
	}
	return 0
}

func (m *StatusQueryResult) GetIp() uint32 {
	if m != nil && m.Ip != nil {
		return *m.Ip
	}
	return 0
}

type StatusQueryResponse struct {
	Resp             *StatusQueryResponse_Type `protobuf:"varint,1,req,name=resp,enum=statuspb.StatusQueryResponse_Type" json:"resp,omitempty"`
	ResumeNetId      *uint32                   `protobuf:"varint,2,req,name=resume_net_id" json:"resume_net_id,omitempty"`
	Result           []*StatusQueryResult      `protobuf:"bytes,3,rep,name=result" json:"result,omitempty"`
	XXX_unrecognized []byte                    `json:"-"`
}

func (m *StatusQueryResponse) Reset()         { *m = StatusQueryResponse{} }
func (m *StatusQueryResponse) String() string { return proto.CompactTextString(m) }
func (*StatusQueryResponse) ProtoMessage()    {}

func (m *StatusQueryResponse) GetResp() StatusQueryResponse_Type {
	if m != nil && m.Resp != nil {
		return *m.Resp
	}
	return StatusQueryResponse_FOUND
}

func (m *StatusQueryResponse) GetResumeNetId() uint32 {
	if m != nil && m.ResumeNetId != nil {
		return *m.ResumeNetId
	}
	return 0
}

func (m *StatusQueryResponse) GetResult() []*StatusQueryResult {
	if m != nil {
		return m.Result
	}
	return nil
}

type StatusMap struct {
	Map              []*StatusMap_KVUserStatus `protobuf:"bytes,1,rep,name=map" json:"map,omitempty"`
	XXX_unrecognized []byte                    `json:"-"`
}

func (m *StatusMap) Reset()         { *m = StatusMap{} }
func (m *StatusMap) String() string { return proto.CompactTextString(m) }
func (*StatusMap) ProtoMessage()    {}

func (m *StatusMap) GetMap() []*StatusMap_KVUserStatus {
	if m != nil {
		return m.Map
	}
	return nil
}

type StatusMap_KVUserStatus struct {
	Key              *uint64                              `protobuf:"varint,1,req" json:"Key,omitempty"`
	Values           []*StatusMap_KVUserStatus_UserStatus `protobuf:"bytes,2,rep" json:"Values,omitempty"`
	XXX_unrecognized []byte                               `json:"-"`
}

func (m *StatusMap_KVUserStatus) Reset()         { *m = StatusMap_KVUserStatus{} }
func (m *StatusMap_KVUserStatus) String() string { return proto.CompactTextString(m) }
func (*StatusMap_KVUserStatus) ProtoMessage()    {}

func (m *StatusMap_KVUserStatus) GetKey() uint64 {
	if m != nil && m.Key != nil {
		return *m.Key
	}
	return 0
}

func (m *StatusMap_KVUserStatus) GetValues() []*StatusMap_KVUserStatus_UserStatus {
	if m != nil {
		return m.Values
	}
	return nil
}

type StatusMap_KVUserStatus_UserStatus struct {
	DeviceId         *string `protobuf:"bytes,1,req,name=device_id" json:"device_id,omitempty"`
	Timestamp        *uint64 `protobuf:"varint,2,req,name=timestamp" json:"timestamp,omitempty"`
	ServerId         *uint32 `protobuf:"varint,3,req,name=server_id" json:"server_id,omitempty"`
	NetId            *uint32 `protobuf:"varint,4,req,name=net_id" json:"net_id,omitempty"`
	AppVersion       *uint32 `protobuf:"varint,5,req,name=app_version" json:"app_version,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *StatusMap_KVUserStatus_UserStatus) Reset()         { *m = StatusMap_KVUserStatus_UserStatus{} }
func (m *StatusMap_KVUserStatus_UserStatus) String() string { return proto.CompactTextString(m) }
func (*StatusMap_KVUserStatus_UserStatus) ProtoMessage()    {}

func (m *StatusMap_KVUserStatus_UserStatus) GetDeviceId() string {
	if m != nil && m.DeviceId != nil {
		return *m.DeviceId
	}
	return ""
}

func (m *StatusMap_KVUserStatus_UserStatus) GetTimestamp() uint64 {
	if m != nil && m.Timestamp != nil {
		return *m.Timestamp
	}
	return 0
}

func (m *StatusMap_KVUserStatus_UserStatus) GetServerId() uint32 {
	if m != nil && m.ServerId != nil {
		return *m.ServerId
	}
	return 0
}

func (m *StatusMap_KVUserStatus_UserStatus) GetNetId() uint32 {
	if m != nil && m.NetId != nil {
		return *m.NetId
	}
	return 0
}

func (m *StatusMap_KVUserStatus_UserStatus) GetAppVersion() uint32 {
	if m != nil && m.AppVersion != nil {
		return *m.AppVersion
	}
	return 0
}

type StringToIntMap struct {
	Map              []*StringToIntMap_STI `protobuf:"bytes,1,rep,name=map" json:"map,omitempty"`
	XXX_unrecognized []byte                `json:"-"`
}

func (m *StringToIntMap) Reset()         { *m = StringToIntMap{} }
func (m *StringToIntMap) String() string { return proto.CompactTextString(m) }
func (*StringToIntMap) ProtoMessage()    {}

func (m *StringToIntMap) GetMap() []*StringToIntMap_STI {
	if m != nil {
		return m.Map
	}
	return nil
}

type StringToIntMap_STI struct {
	Str              *string `protobuf:"bytes,1,req,name=str" json:"str,omitempty"`
	Intger           *uint32 `protobuf:"varint,2,req,name=intger" json:"intger,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *StringToIntMap_STI) Reset()         { *m = StringToIntMap_STI{} }
func (m *StringToIntMap_STI) String() string { return proto.CompactTextString(m) }
func (*StringToIntMap_STI) ProtoMessage()    {}

func (m *StringToIntMap_STI) GetStr() string {
	if m != nil && m.Str != nil {
		return *m.Str
	}
	return ""
}

func (m *StringToIntMap_STI) GetIntger() uint32 {
	if m != nil && m.Intger != nil {
		return *m.Intger
	}
	return 0
}

type AnonymousMap struct {
	Map              []*AnonymousMap_KVAnonymousEntry `protobuf:"bytes,1,rep,name=map" json:"map,omitempty"`
	XXX_unrecognized []byte                           `json:"-"`
}

func (m *AnonymousMap) Reset()         { *m = AnonymousMap{} }
func (m *AnonymousMap) String() string { return proto.CompactTextString(m) }
func (*AnonymousMap) ProtoMessage()    {}

func (m *AnonymousMap) GetMap() []*AnonymousMap_KVAnonymousEntry {
	if m != nil {
		return m.Map
	}
	return nil
}

type AnonymousMap_KVAnonymousEntry struct {
	Key              *string                                         `protobuf:"bytes,1,req" json:"Key,omitempty"`
	Values           []*AnonymousMap_KVAnonymousEntry_AnonymousEntry `protobuf:"bytes,2,rep" json:"Values,omitempty"`
	XXX_unrecognized []byte                                          `json:"-"`
}

func (m *AnonymousMap_KVAnonymousEntry) Reset()         { *m = AnonymousMap_KVAnonymousEntry{} }
func (m *AnonymousMap_KVAnonymousEntry) String() string { return proto.CompactTextString(m) }
func (*AnonymousMap_KVAnonymousEntry) ProtoMessage()    {}

func (m *AnonymousMap_KVAnonymousEntry) GetKey() string {
	if m != nil && m.Key != nil {
		return *m.Key
	}
	return ""
}

func (m *AnonymousMap_KVAnonymousEntry) GetValues() []*AnonymousMap_KVAnonymousEntry_AnonymousEntry {
	if m != nil {
		return m.Values
	}
	return nil
}

type AnonymousMap_KVAnonymousEntry_AnonymousEntry struct {
	AppVersion       *uint32 `protobuf:"varint,1,req,name=app_version" json:"app_version,omitempty"`
	Timestamp        *uint64 `protobuf:"varint,2,req,name=timestamp" json:"timestamp,omitempty"`
	NetId            *uint32 `protobuf:"varint,3,req,name=net_id" json:"net_id,omitempty"`
	ServerId         *uint32 `protobuf:"varint,4,req,name=server_id" json:"server_id,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *AnonymousMap_KVAnonymousEntry_AnonymousEntry) Reset() {
	*m = AnonymousMap_KVAnonymousEntry_AnonymousEntry{}
}
func (m *AnonymousMap_KVAnonymousEntry_AnonymousEntry) String() string {
	return proto.CompactTextString(m)
}
func (*AnonymousMap_KVAnonymousEntry_AnonymousEntry) ProtoMessage() {}

func (m *AnonymousMap_KVAnonymousEntry_AnonymousEntry) GetAppVersion() uint32 {
	if m != nil && m.AppVersion != nil {
		return *m.AppVersion
	}
	return 0
}

func (m *AnonymousMap_KVAnonymousEntry_AnonymousEntry) GetTimestamp() uint64 {
	if m != nil && m.Timestamp != nil {
		return *m.Timestamp
	}
	return 0
}

func (m *AnonymousMap_KVAnonymousEntry_AnonymousEntry) GetNetId() uint32 {
	if m != nil && m.NetId != nil {
		return *m.NetId
	}
	return 0
}

func (m *AnonymousMap_KVAnonymousEntry_AnonymousEntry) GetServerId() uint32 {
	if m != nil && m.ServerId != nil {
		return *m.ServerId
	}
	return 0
}

func init() {
	proto.RegisterEnum("statuspb.StatusRequest_Type", StatusRequest_Type_name, StatusRequest_Type_value)
	proto.RegisterEnum("statuspb.StatusRequest_FieldType", StatusRequest_FieldType_name, StatusRequest_FieldType_value)
	proto.RegisterEnum("statuspb.StatusResponse_Type", StatusResponse_Type_name, StatusResponse_Type_value)
	proto.RegisterEnum("statuspb.StatusQueryResponse_Type", StatusQueryResponse_Type_name, StatusQueryResponse_Type_value)
}
