// Code generated by protoc-gen-go.
// source: upstreampb.proto
// DO NOT EDIT!

/*
Package upstreampb is a generated protocol buffer package.

It is generated from these files:
	upstreampb.proto

It has these top-level messages:
	UpstreamRequest
	UpstreamResponse
*/
package upstreampb

import proto "github.com/golang/protobuf/proto"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = math.Inf

type UpstreamRequest_FieldType int32

const (
	UpstreamRequest_UID      UpstreamRequest_FieldType = 0
	UpstreamRequest_DEVICEID UpstreamRequest_FieldType = 1
)

var UpstreamRequest_FieldType_name = map[int32]string{
	0: "UID",
	1: "DEVICEID",
}
var UpstreamRequest_FieldType_value = map[string]int32{
	"UID":      0,
	"DEVICEID": 1,
}

func (x UpstreamRequest_FieldType) Enum() *UpstreamRequest_FieldType {
	p := new(UpstreamRequest_FieldType)
	*p = x
	return p
}
func (x UpstreamRequest_FieldType) String() string {
	return proto.EnumName(UpstreamRequest_FieldType_name, int32(x))
}
func (x *UpstreamRequest_FieldType) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(UpstreamRequest_FieldType_value, data, "UpstreamRequest_FieldType")
	if err != nil {
		return err
	}
	*x = UpstreamRequest_FieldType(value)
	return nil
}

type UpstreamRequest struct {
	NetId            *uint32                    `protobuf:"varint,1,req,name=net_id" json:"net_id,omitempty"`
	ReqId            *uint32                    `protobuf:"varint,2,req,name=req_id" json:"req_id,omitempty"`
	FieldType        *UpstreamRequest_FieldType `protobuf:"varint,3,req,name=field_type,enum=upstreampb.UpstreamRequest_FieldType" json:"field_type,omitempty"`
	Uid              *uint64                    `protobuf:"varint,4,opt,name=uid" json:"uid,omitempty"`
	DeviceId         *string                    `protobuf:"bytes,5,opt,name=device_id" json:"device_id,omitempty"`
	Body             *string                    `protobuf:"bytes,6,req,name=body" json:"body,omitempty"`
	XXX_unrecognized []byte                     `json:"-"`
}

func (m *UpstreamRequest) Reset()         { *m = UpstreamRequest{} }
func (m *UpstreamRequest) String() string { return proto.CompactTextString(m) }
func (*UpstreamRequest) ProtoMessage()    {}

func (m *UpstreamRequest) GetNetId() uint32 {
	if m != nil && m.NetId != nil {
		return *m.NetId
	}
	return 0
}

func (m *UpstreamRequest) GetReqId() uint32 {
	if m != nil && m.ReqId != nil {
		return *m.ReqId
	}
	return 0
}

func (m *UpstreamRequest) GetFieldType() UpstreamRequest_FieldType {
	if m != nil && m.FieldType != nil {
		return *m.FieldType
	}
	return UpstreamRequest_UID
}

func (m *UpstreamRequest) GetUid() uint64 {
	if m != nil && m.Uid != nil {
		return *m.Uid
	}
	return 0
}

func (m *UpstreamRequest) GetDeviceId() string {
	if m != nil && m.DeviceId != nil {
		return *m.DeviceId
	}
	return ""
}

func (m *UpstreamRequest) GetBody() string {
	if m != nil && m.Body != nil {
		return *m.Body
	}
	return ""
}

type UpstreamResponse struct {
	NetId            *uint32 `protobuf:"varint,1,req,name=net_id" json:"net_id,omitempty"`
	ReqId            *uint32 `protobuf:"varint,2,req,name=req_id" json:"req_id,omitempty"`
	Body             *string `protobuf:"bytes,3,req,name=body" json:"body,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *UpstreamResponse) Reset()         { *m = UpstreamResponse{} }
func (m *UpstreamResponse) String() string { return proto.CompactTextString(m) }
func (*UpstreamResponse) ProtoMessage()    {}

func (m *UpstreamResponse) GetNetId() uint32 {
	if m != nil && m.NetId != nil {
		return *m.NetId
	}
	return 0
}

func (m *UpstreamResponse) GetReqId() uint32 {
	if m != nil && m.ReqId != nil {
		return *m.ReqId
	}
	return 0
}

func (m *UpstreamResponse) GetBody() string {
	if m != nil && m.Body != nil {
		return *m.Body
	}
	return ""
}

func init() {
	proto.RegisterEnum("upstreampb.UpstreamRequest_FieldType", UpstreamRequest_FieldType_name, UpstreamRequest_FieldType_value)
}
