// Code generated by protoc-gen-gogo.
// source: pushpb_gogo.proto
// DO NOT EDIT!

/*
Package pushpb_gogo is a generated protocol buffer package.

It is generated from these files:
	pushpb_gogo.proto

It has these top-level messages:
	PushRequestFromUpstream
	PushRequestToDownstream
*/
package pushpb_gogo

import testing "testing"
import math_rand "math/rand"
import github_com_gogo_protobuf_proto "github.com/gogo/protobuf/proto"

func BenchmarkPushRequestFromUpstreamProtoMarshal(b *testing.B) {
	popr := math_rand.New(math_rand.NewSource(616))
	total := 0
	pops := make([]*PushRequestFromUpstream, 10000)
	for i := 0; i < 10000; i++ {
		pops[i] = NewPopulatedPushRequestFromUpstream(popr, false)
	}
	b.ResetTimer()
	for i := 0; i < b.N; i++ {
		data, err := github_com_gogo_protobuf_proto.Marshal(pops[i%10000])
		if err != nil {
			panic(err)
		}
		total += len(data)
	}
	b.SetBytes(int64(total / b.N))
}

func BenchmarkPushRequestFromUpstreamProtoUnmarshal(b *testing.B) {
	popr := math_rand.New(math_rand.NewSource(616))
	total := 0
	datas := make([][]byte, 10000)
	for i := 0; i < 10000; i++ {
		data, err := github_com_gogo_protobuf_proto.Marshal(NewPopulatedPushRequestFromUpstream(popr, false))
		if err != nil {
			panic(err)
		}
		datas[i] = data
	}
	msg := &PushRequestFromUpstream{}
	b.ResetTimer()
	for i := 0; i < b.N; i++ {
		total += len(datas[i%10000])
		if err := github_com_gogo_protobuf_proto.Unmarshal(datas[i%10000], msg); err != nil {
			panic(err)
		}
	}
	b.SetBytes(int64(total / b.N))
}

func BenchmarkPushRequestToDownstreamProtoMarshal(b *testing.B) {
	popr := math_rand.New(math_rand.NewSource(616))
	total := 0
	pops := make([]*PushRequestToDownstream, 10000)
	for i := 0; i < 10000; i++ {
		pops[i] = NewPopulatedPushRequestToDownstream(popr, false)
	}
	b.ResetTimer()
	for i := 0; i < b.N; i++ {
		data, err := github_com_gogo_protobuf_proto.Marshal(pops[i%10000])
		if err != nil {
			panic(err)
		}
		total += len(data)
	}
	b.SetBytes(int64(total / b.N))
}

func BenchmarkPushRequestToDownstreamProtoUnmarshal(b *testing.B) {
	popr := math_rand.New(math_rand.NewSource(616))
	total := 0
	datas := make([][]byte, 10000)
	for i := 0; i < 10000; i++ {
		data, err := github_com_gogo_protobuf_proto.Marshal(NewPopulatedPushRequestToDownstream(popr, false))
		if err != nil {
			panic(err)
		}
		datas[i] = data
	}
	msg := &PushRequestToDownstream{}
	b.ResetTimer()
	for i := 0; i < b.N; i++ {
		total += len(datas[i%10000])
		if err := github_com_gogo_protobuf_proto.Unmarshal(datas[i%10000], msg); err != nil {
			panic(err)
		}
	}
	b.SetBytes(int64(total / b.N))
}

func BenchmarkPushRequestFromUpstreamSize(b *testing.B) {
	popr := math_rand.New(math_rand.NewSource(616))
	total := 0
	pops := make([]*PushRequestFromUpstream, 1000)
	for i := 0; i < 1000; i++ {
		pops[i] = NewPopulatedPushRequestFromUpstream(popr, false)
	}
	b.ResetTimer()
	for i := 0; i < b.N; i++ {
		total += pops[i%1000].Size()
	}
	b.SetBytes(int64(total / b.N))
}

func BenchmarkPushRequestToDownstreamSize(b *testing.B) {
	popr := math_rand.New(math_rand.NewSource(616))
	total := 0
	pops := make([]*PushRequestToDownstream, 1000)
	for i := 0; i < 1000; i++ {
		pops[i] = NewPopulatedPushRequestToDownstream(popr, false)
	}
	b.ResetTimer()
	for i := 0; i < b.N; i++ {
		total += pops[i%1000].Size()
	}
	b.SetBytes(int64(total / b.N))
}

//These tests are generated by github.com/gogo/protobuf/plugin/testgen
